'use strict';

// ---------------------------------------------------------------------------
// Thread handoff backend: the brief a thread writes when its conversation is
// handed to another thread. Briefs live under `.hivemind/handoffs/` inside the
// board's project directory:
//
//   .hivemind/handoffs/<id>.md   -- written by the SOURCE thread (the brief)
//
// Hivemind never writes the brief itself: only the source agent knows what
// mattered in its own context, so it is asked to write the file and Hivemind
// just watches for it to land (readHandoff) before pointing the target thread
// at the same path. `id` is generated by the renderer per handoff.
//
// Same house style as plan.js / promptHistory.js: every path is resolved and
// checked to stay inside `.hivemind/handoffs`, so a stray id can't read or
// delete outside the project.
// ---------------------------------------------------------------------------

const fs = require('fs');
const path = require('path');

const HANDOFFS_REL = '.hivemind/handoffs';

// Briefs are disposable — once the target thread has read one it is only
// history. Sweep anything older than a week so the folder can't grow forever
// (same treatment as staged codex attachments in main.js).
const MAX_AGE_MS = 7 * 24 * 60 * 60 * 1000;

// Resolve `.hivemind/handoffs/<id>.md` against the project root and reject
// anything that escapes it (or an id carrying path separators / traversal).
// Returns the absolute path, or null.
function handoffPath(root, id) {
  if (typeof root !== 'string' || !root.length) return null;
  if (typeof id !== 'string' || !/^[A-Za-z0-9._-]+$/.test(id)) return null;
  const base = path.resolve(root);
  const dir = path.resolve(base, HANDOFFS_REL);
  const resolved = path.resolve(dir, id + '.md');
  if (resolved !== dir && !resolved.startsWith(dir + path.sep)) return null;
  return resolved;
}

// The project-relative path both threads are told to use. Kept here so the
// renderer's prompt text and this module's guard can never disagree.
function handoffRelPath(id) {
  return HANDOFFS_REL + '/' + id + '.md';
}

// Read a brief. A missing file is the normal "the thread hasn't written it
// yet" state the renderer polls on, not an error. `mtime` comes back so the
// caller can wait for the file to stop changing before acting on it — an agent
// may write a draft and then revise it, and handing the target a half-written
// brief loses the rest.
async function readHandoff(root, id) {
  const p = handoffPath(root, id);
  if (!root) return { ok: false, reason: 'no-dir' };
  if (!p) return { ok: false, reason: 'error', message: 'Invalid handoff path.' };
  try {
    const content = await fs.promises.readFile(p, 'utf8');
    const { mtimeMs } = await fs.promises.stat(p);
    return { ok: true, content, mtime: mtimeMs };
  } catch (err) {
    if (err.code === 'ENOENT') return { ok: false, reason: 'not-found' };
    return { ok: false, reason: 'error', message: err.message };
  }
}

// Delete one brief. A missing file is already cleared, not a failure.
async function clearHandoff(root, id) {
  const p = handoffPath(root, id);
  if (!p) return { ok: false, message: 'Invalid handoff path.' };
  try {
    await fs.promises.unlink(p);
    return { ok: true };
  } catch (err) {
    if (err.code === 'ENOENT') return { ok: true };
    return { ok: false, message: err.message };
  }
}

// Drop briefs older than a week. Best-effort: a missing folder (no handoff has
// ever happened here) and an unreadable entry are both fine, and a sweep that
// fails must never block the handoff it was called ahead of.
async function sweepHandoffs(root) {
  if (typeof root !== 'string' || !root.length) return { ok: false, reason: 'no-dir' };
  const dir = path.resolve(path.resolve(root), HANDOFFS_REL);
  let names;
  try {
    names = await fs.promises.readdir(dir);
  } catch (err) {
    if (err.code === 'ENOENT') return { ok: true, removed: 0 };
    return { ok: false, message: err.message };
  }
  const cutoff = Date.now() - MAX_AGE_MS;
  let removed = 0;
  for (const name of names) {
    if (!name.endsWith('.md')) continue;
    const p = path.join(dir, name);
    try {
      const { mtimeMs } = await fs.promises.stat(p);
      if (mtimeMs >= cutoff) continue;
      await fs.promises.unlink(p);
      removed++;
    } catch (_) { /* vanished or locked — leave it for the next sweep */ }
  }
  return { ok: true, removed };
}

module.exports = { readHandoff, clearHandoff, sweepHandoffs, handoffRelPath };
